### PR TITLE
STROOSUP-559: adding support for nodejs pack with source and package …

### PR DESCRIPTION
**Pull request by ighouri**
…installation

### CODE REVIEW

**Comment by schwankl** [comment]
this was already fixed in the node component you are trying to delete.  There is no reason to support old os-package versions of node...  Decision was to be binary only - verified already w/ Michael Fischer

**Comment by schwankl** [comment]
see https://github.com/oneops/circuit-oneops-1/commit/a5598768b01de3f2fcf29ccbb160501f7edd2d48 ... this also allows newer versions to be used without code change

**Comment by ighouri** [comment]
@schwankl 

1). I have removed the package and source installation of nodejs.

**Comment by schwankl** [comment]
discussed w/ ighouri over slack - folks will continue to use node pack

**Pull request closed without merging**
