### PR TITLE
Move detach azuredatadisk to volume step from storage step

### PR DESCRIPTION
**Pull request by kowsalyapalaniappan**
Changes to stabilize azuredatadisk, moved attaching and detaching to volume recipes instead of storage rceipe, refactored azuredatadisk to use LWRP

### CODE REVIEW

**Comment by schwankl** [comment]
will merge after /myScript stuff is converted to /opt/oneops/azure-restore-ephemeral-device script we discussed

**Comment by kowsalyapalaniappan** [comment]
Followed up the review comments , moved myScripts to /opt/oneops/azure-restore-ephemeral-mntpts/, removed unnecessary details variable, removed additional block for lvremove for azure
Added check before adding restore script to rc.local.

**Comment by kowsalyapalaniappan** [comment]
@schwankl could you please merge this PR ?

**Comment by kowsalyapalaniappan** [comment]
i reverted the change to handle _0 scenario.

**Comment by kowsalyapalaniappan** [comment]
I resolved the merge conflict.

**Pull request merged**
